import base64
import binascii
import hashlib
import importlib
import re

from .analysis import (
    bigram_frequency,
    letter_frequency,
    ngram_distance,
    phonetic_alphabet_d,
    phonetic_alphabet_e,
    return_phonetic_alphabet_values,
    trigram_frequency,
)
from .adfgvx import adfgx_d, adfgx_e, adfgvx_d, adfgvx_e
from .braille import braille_d, braille_ja_d
from .base_conversion import (
    base_a_to_base_b,
    base_a_to_base_b_onenumber,
    char_to_codepoint,
    codepoint_to_char,
    valid_chars_for_base_n,
)
from .affine import affine_d, affine_d_a, affine_e, affine_e_a
from .code_tables import (
    list_0,
    list_A,
    list_a,
    polybius_table,
    spelling_alphabet_icao_1947_1,
    spelling_alphabet_icao_1947_2,
    spelling_alphabet_icao_1949,
    spelling_alphabet_icao_1951,
    spelling_alphabet_icao_2008,
)
from .common import (
    assign_digits,
    extract_integer_only,
    mixed_alphabet,
    mixed_alphanumeric,
    replace_all,
    replace_all_case_insensitive,
    unique,
    unique_list,
)
from .enigma import enigma, plugboard_gen
from .purple import purple_decode, purple_encode
from .kakushi import kakushi_encode, kakushi_decode
from .math_functions import factorize, xgcd
from .morse import bacon1_d, bacon1_e, bacon2_d, bacon2_e, morse_d, morse_e, morse_wabun_d, morse_wabun_e
from .misc import password_generate
from .polybius_playfair import (
    bifid_d,
    bifid_e,
    playfair_a,
    playfair_d,
    playfair_d6,
    playfair_e,
    playfair_e6,
    polybius_d,
    polybius_e,
)
from .rot_vigenere import (
    atbash,
    beaufort,
    hexbash,
    rot,
    rot_a,
    vig_a,
    vig_d,
    vig_d_auto,
    vig_e,
    vig_e_auto,
)
from .tables import (
    return_japan_traditional_month_names_list,
    return_japanese_zodiac_list,
    return_zodiac_list,
)
from .text_utils import (
    abc012,
    chemical_symbol_convert,
    hiragana_to_katakana,
    kw,
    split_dakuten,
    table_subtitution,
    text_split,
)
from .transposition import (
    columnar_d,
    columnar_e,
    railfence_d,
    railfence_e,
    rect,
    rect_reverse_even,
    rev,
    skip_d,
    skip_e,
    swap_xy_axes,
)
from .rsa import rsa_decode, rsa_encode
from .uuencode import uu_decode, uu_encode
from .vanity import auto_split_number_string, vanity_d, vanity_e

__all__ = [
    "abc012",
    "adfgx_d",
    "adfgx_e",
    "adfgvx_d",
    "adfgvx_e",
    "affine_d",
    "affine_d_a",
    "affine_e",
    "affine_e_a",
    "assign_digits",
    "atbash",
    "auto_split_number_string",
    "base_a_to_base_b",
    "base_a_to_base_b_onenumber",
    "beaufort",
    "bifid_d",
    "bifid_e",
    "bigram_frequency",
    "braille_d",
    "braille_ja_d",
    "char_to_codepoint",
    "chemical_symbol_convert",
    "codepoint_to_char",
    "columnar_d",
    "columnar_e",
    "enigma",
    "extract_integer_only",
    "factorize",
    "hexbash",
    "hiragana_to_katakana",
    "kakushi_decode",
    "kakushi_encode",
    "kw",
    "letter_frequency",
    "list_0",
    "list_A",
    "list_a",
    "mixed_alphabet",
    "mixed_alphanumeric",
    "morse_d",
    "morse_e",
    "morse_wabun_d",
    "morse_wabun_e",
    "ngram_distance",
    "password_generate",
    "phonetic_alphabet_d",
    "phonetic_alphabet_e",
    "playfair_d",
    "playfair_d6",
    "playfair_e",
    "playfair_e6",
    "plugboard_gen",
    "polybius_d",
    "polybius_e",
    "purple_decode",
    "purple_encode",
    "railfence_d",
    "railfence_e",
    "rect",
    "rect_reverse_even",
    "replace_all",
    "replace_all_case_insensitive",
    "return_japan_traditional_month_names_list",
    "return_japanese_zodiac_list",
    "return_phonetic_alphabet_values",
    "return_zodiac_list",
    "rev",
    "rot",
    "rot_a",
    "rsa_decode",
    "rsa_encode",
    "skip_d",
    "skip_e",
    "spelling_alphabet_icao_1947_1",
    "spelling_alphabet_icao_1947_2",
    "spelling_alphabet_icao_1949",
    "spelling_alphabet_icao_1951",
    "spelling_alphabet_icao_2008",
    "split_dakuten",
    "swap_xy_axes",
    "table_subtitution",
    "text_split",
    "trigram_frequency",
    "unique",
    "unique_list",
    "uu_decode",
    "uu_encode",
    "valid_chars_for_base_n",
    "vanity_d",
    "vanity_e",
    "vig_a",
    "vig_d",
    "vig_d_auto",
    "vig_e",
    "vig_e_auto",
    "xgcd",
]
