from copy import deepcopy


CATEGORY_DEFINITIONS = [
    {"id": "cryptography", "title": "Cryptography"},
    {"id": "encoding", "title": "Encoding"},
    {"id": "utility", "title": "Utility"},
    {"id": "ingress-tools", "title": "Remember Ingress"},
    {"id": "extra-pages", "title": "Extra"},
]


CATEGORY_TOOL_ORDER = {
    "cryptography": [
        "rot",
        "vigenere",
        "simplesub",
        "affine",
        "polybius",
        "playfair",
        "bifid",
        "purple",
        "enigma",
        "reverse",
        "rectangle",
        "railfence",
        "columnar",
        "skip",
    ],
    "encoding": [
        "base64",
        "morse",
        "charcode",
        "braille",
        "braille_ja",
        "phonetic",
        "vanity",
        "kakushi",
    ],
    "utility": [
        "prime",
        "number_conv",
        "charreplace",
        "split_text",
        "hash",
        "pwgen",
        "resize",
        "riddle_tables",   
        "swap_xy",
        "frequency",
        "rsa",
        "memo",
    ],
    "ingress-tools": [
        "rot_ex",
        "vigenere_ex",
        "rectangle_ex",
        "charcode_ex",
        "ingress_keywords",
        "niantic_wiki",
    ],
    "extra-pages": [
        "challenge",
        "passcode",
        "link",
        "about",
    ],
}


TOOL_CATALOG = [
    {
        "id": "rot",
        "path": "/rot",
        "name": "ROT",
        "description": "Rotate text by a fixed alphabet shift.",
        "aliases": ["caesar", "caesar cipher", "shift cipher", "rot13", "rotate"],
        "tags": ["cipher", "substitution", "classical"],
        "icon": "icon_rot.png",
    },
    {
        "id": "vigenere",
        "path": "/vigenere",
        "name": "Vigenere",
        "description": "Encode and decode Vigenere cipher text.",
        "aliases": ["vigenere cipher", "keyword cipher"],
        "tags": ["cipher", "polyalphabetic", "classical","beaufort","gronsfeld","auto key"],
        "icon": "icon_vigenere.png",
    },
    {
        "id": "simplesub",
        "path": "/simplesub",
        "name": "Simple Substitutions",
        "description": "Work with monoalphabetic substitution tables.",
        "aliases": ["simple substitution", "monoalphabetic substitution","tables"],
        "tags": ["cipher", "substitution", "classical","A-a swap","Atbash","Morse","keyboard","Dvorak","MALTRON"],
        "icon": "icon_simplesub.png",
    },
    {
        "id": "affine",
        "path": "/affine",
        "name": "Affine",
        "description": "Encode and decode affine substitution ciphers.",
        "aliases": ["affine cipher","linear"],
        "tags": ["cipher", "substitution", "classical"],
        "icon": "icon_affine.png",
    },
    {
        "id": "polybius",
        "path": "/polybius",
        "name": "Polybius",
        "description": "Convert text with a Polybius square.",
        "aliases": ["polybius square"],
        "tags": ["cipher", "substitution", "classical"],
        "icon": "icon_polybius.png",
    },
    {
        "id": "playfair",
        "path": "/playfair",
        "name": "Playfair",
        "description": "Encode and decode Playfair digraph ciphers.",
        "aliases": ["playfair cipher"],
        "tags": ["cipher", "digraph", "classical","matrix"],
        "icon": "icon_playfair.png",
    },
    {
        "id": "bifid",
        "path": "/bifid",
        "name": "Bifid",
        "description": "Encode and decode Bifid ciphers.",
        "aliases": ["bifid cipher"],
        "tags": ["cipher", "fractionation", "classical"],
        "icon": "icon_bifid.png",
    },
    {
        "id": "purple",
        "path": "/purple",
        "name": "Purple",
        "description": "Run the Japanese Purple cipher simulation.",
        "aliases": ["purple cipher","Japan"],
        "tags": ["cipher", "machine", "ww2"],
        "icon": "icon_purple.png",
    },
    {
        "id": "enigma",
        "path": "/enigma",
        "name": "Enigma",
        "description": "Run the Enigma machine simulation.",
        "aliases": ["enigma machine"],
        "tags": ["cipher", "machine", "ww2"],
        "icon": "icon_enigma.png",
    },
    {
        "id": "reverse",
        "path": "/reverse",
        "name": "Reverse",
        "description": "Reverse text order for quick transposition checks.",
        "aliases": ["reverse text", "backwards"],
        "tags": ["transposition", "cipher", "text", "classical"],
        "icon": "icon_reverse.png",
    },
    {
        "id": "rectangle",
        "path": "/rectangle",
        "name": "Rectangle",
        "description": "Explore rectangle transposition patterns.",
        "aliases": ["rectangle cipher", "grid transposition"],
        "tags": ["transposition", "cipher", "analysis", "classical","ingress","zig-zag","zigzag"],
        "icon": "icon_rectangle.png",
    },
    {
        "id": "railfence",
        "path": "/railfence",
        "name": "Railfence",
        "description": "Encode and decode rail fence ciphers.",
        "aliases": ["rail fence", "zigzag cipher"],
        "tags": ["transposition", "cipher", "classical","zig-zag"],
        "icon": "icon_railfence.png",
    },
    {
        "id": "columnar",
        "path": "/columnar",
        "name": "Columnar",
        "description": "Work with columnar transposition ciphers.",
        "aliases": ["columnar transposition"],
        "tags": ["transposition", "cipher", "classical"],
        "icon": "icon_columnar.png",
    },
    {
        "id": "skip",
        "path": "/skip",
        "name": "Skip",
        "description": "Read text with skip patterns.",
        "aliases": ["skip cipher"],
        "tags": ["transposition", "cipher", "classical"],
        "icon": "icon_skip.png",
    },
    {
        "id": "swap_xy",
        "path": "/swap_xy",
        "name": "Swap X-Y Axes",
        "description": "Transpose text laid out on a grid.",
        "aliases": ["swap xy", "transpose grid"],
        "tags": ["transposition", "grid"],
        "icon": "icon_swap_xy.png",
    },
    {
        "id": "frequency",
        "path": "/frequency",
        "name": "Frequency Analysis",
        "description": "Count letters and n-grams for cipher analysis.",
        "aliases": ["letter frequency", "frequency count"],
        "tags": ["analysis", "cipher", "statistics","n-gram"],
        "icon": "icon_frequency.png",
    },
    {
        "id": "rsa",
        "path": "/rsa",
        "name": "RSA",
        "description": "Encode and decode simple RSA examples.",
        "aliases": ["rsa cipher", "public key"],
        "tags": ["mathematics", "modern", "public-key"],
        "icon": "icon_rsa.png",
    },
    {
        "id": "base64",
        "path": "/base64",
        "name": "Base64 etc.",
        "description": "Encode and decode base family formats.",
        "aliases": ["base64", "base32", "base58", "base85"],
        "tags": ["encode", "decode", "base"],
        "icon": "icon_base64.png",
    },
    {
        "id": "morse",
        "path": "/morse",
        "name": "Morse",
        "description": "Translate text and Morse code.",
        "aliases": ["morse code","dots and dashes","dits and dahs"],
        "tags": ["encode", "decode","Japan"],
        "icon": "icon_morse.png",
    },
    {
        "id": "charcode",
        "path": "/charcode",
        "name": "Character Code",
        "description": "Convert text to character code representations.",
        "aliases": ["ascii", "unicode", "character code"],
        "tags": ["encode", "decode", "codepoint", "text"],
        "icon": "icon_charcode.png",
    },
    {
        "id": "braille",
        "path": "/braille",
        "name": "Braille",
        "description": "Convert text and Braille notation.",
        "aliases": ["braille code"],
        "tags": ["blind"],
        "icon": "icon_braille.png",
    },
    {
        "id": "braille_ja",
        "path": "/braille_ja",
        "name": "Japanese Braille",
        "description": "Convert Japanese text and Braille notation.",
        "aliases": ["japanese braille", "tenji"],
        "tags": ["blind","Japan"],
        "icon": "icon_braille_ja.png",
    },
    {
        "id": "phonetic",
        "path": "/phonetic",
        "name": "Phonetic",
        "description": "Render text in phonetic alphabet forms.",
        "aliases": ["nato phonetic", "phonetic alphabet"],
        "tags": ["alphabet"],
        "icon": "icon_phonetic.png",
    },
    {
        "id": "vanity",
        "path": "/vanity",
        "name": "Vanity Number",
        "description": "Convert between text and phone keypad numbers.",
        "aliases": ["phone keypad", "t9", "vanity"],
        "tags": ["phone", "number"],
        "icon": "icon_vanity.png",
    },
    {
        "id": "kakushi",
        "path": "/kakushi",
        "name": "Kakushi",
        "description": "Convert hidden text patterns used in puzzles.",
        "aliases": ["hidden text", "kakushi code"],
        "tags": ["encode","decode", "original", "japan","a3xgvo"],
        "icon": "icon_kakushi.png",
    },
    {
        "id": "charreplace",
        "path": "/charreplace",
        "name": "Character Replace",
        "description": "Replace characters in bulk.",
        "aliases": ["character replace", "replace text"],
        "tags": ["text", "replace", "transform","utility"],
        "icon": "icon_charreplace.png",
    },
    {
        "id": "split_text",
        "path": "/split_text",
        "name": "Split Text",
        "description": "Split text into fixed lengths or groups.",
        "aliases": ["split text", "chunk text"],
        "tags": ["text", "split", "format","utility"],
        "icon": "icon_split_text.png",
    },
    {
        "id": "memo",
        "path": "/memo",
        "name": "Memo",
        "description": "Open a simple scratchpad page.",
        "aliases": ["notes", "memo pad"],
        "tags": ["text", "utility", "notes"],
        "icon": "icon_memo.png",
    },
    {
        "id": "prime",
        "path": "/prime",
        "name": "Prime Decomposition",
        "description": "Factor integers into primes.",
        "aliases": ["prime factorization", "prime decomposition"],
        "tags": ["number", "math", "prime","factor"],
        "icon": "icon_prime.png",
    },
    {
        "id": "number_conv",
        "path": "/number_conv",
        "name": "Number Conversion",
        "description": "Convert numbers between bases.",
        "aliases": ["base conversion", "radix conversion"],
        "tags": ["number", "base", "math"],
        "icon": "icon_number_conv.png",
    },
    {
        "id": "hash",
        "path": "/hash",
        "name": "Hash",
        "description": "Generate common hash digests from text.",
        "aliases": ["sha", "md5", "sha256", "hash generator"],
        "tags": ["utility", "crypto", "digest"],
        "icon": "icon_hash.png",
    },
    {
        "id": "pwgen",
        "path": "/pwgen",
        "name": "Password Generator",
        "description": "Generate random passwords.",
        "aliases": ["password generator", "pwgen"],
        "tags": ["utility", "password", "random"],
        "icon": "icon_pwgen.png",
    },
    {
        "id": "resize",
        "path": "/resize",
        "name": "Resize Image",
        "description": "Resize and pad uploaded images.",
        "aliases": ["image resize", "resize image"],
        "tags": ["utility", "image", "resize","picture"],
        "icon": "icon_resize.png",
    },
    {
        "id": "riddle_tables",
        "path": "/riddle_tables",
        "name": "Riddle Tables",
        "description": "Browse handy puzzle and cipher reference tables.",
        "aliases": ["riddle tables", "reference tables"],
        "tags": ["utility", "reference", "puzzle","Japan","Traditional month","zodiac","keyboard"],
        "icon": "icon_riddle_tables.png",
    },
    {
        "id": "rot_ex",
        "path": "/rot_ex",
        "name": "Rot ex",
        "description": "Ingress-oriented ROT helper.",
        "aliases": ["caesar", "caesar cipher", "shift cipher", "rot13", "rotate"],
        "tags": ["cipher", "substitution", "classical","ingress","atbash"],
        "icon": "icon_rot_ex.png",
    },
    {
        "id": "vigenere_ex",
        "path": "/vigenere_ex",
        "name": "Vigenere ex",
        "description": "Ingress-oriented Vigenere helper.",
        "aliases": ["vigenere cipher", "keyword cipher"],
        "tags": ["cipher", "polyalphabetic", "classical","beaufort","gronsfeld","auto key","ingress"],
        "icon": "icon_vigenere_ex.png",
    },
    {
        "id": "rectangle_ex",
        "path": "/rectangle_ex",
        "name": "Rectangle ex",
        "description": "Ingress-oriented rectangle helper.",
        "aliases": ["rectangle ex", "ingress rectangle"],
        "tags": ["ingress", "cipher", "rectangle"],
        "icon": "icon_rectangle_ex.png",
    },
    {
        "id": "charcode_ex",
        "path": "/charcode_ex",
        "name": "Character Code ex",
        "description": "Ingress-oriented character code helper.",
        "aliases": ["character code ex", "ingress charcode"],
        "tags": ["ingress", "encoding", "charcode"],
        "icon": "icon_charcode_ex.png",
    },
    {
        "id": "ingress_keywords",
        "path": "/ingress_keywords",
        "name": "Keywords",
        "description": "Browse Ingress keyword references.",
        "aliases": ["ingress keywords"],
        "tags": ["ingress", "keywords", "reference"],
        "icon": "icon_ingress_keywords.png",
    },
    {
        "id": "niantic_wiki",
        "path": "/niantic_wiki/page/start.html",
        "name": "Niantic Wiki",
        "description": "Browse the imported Niantic Wiki archive.",
        "aliases": ["niantic project wiki", "niantic wiki archive"],
        "tags": ["ingress", "archive", "reference", "wiki","schlarp"],
        "icon": "icon_niantic_wiki.png",
    },
    {
        "id": "challenge",
        "path": "/challenge/",
        "name": "Cipher Challenge",
        "description": "Play original cipher challenge pages.",
        "aliases": ["cipher challenge", "challenge"],
        "tags": ["challenge", "puzzle", "cipher"],
        "icon": "icon_cryptobrella.png",
    },
    {
        "id": "passcode",
        "path": "/passcode",
        "name": "Passcode Challenge",
        "description": "Play the Ingress Passcode Challenge.",
        "aliases": ["passcode challenge", "ingress passcode"],
        "tags": ["challenge", "passcode", "ingress"],
        "icon": "icon_passcode.png",
    },
    {
        "id": "link",
        "path": "/link",
        "name": "Link",
        "description": "Open related links and references.",
        "aliases": ["links", "reference links"],
        "tags": ["links", "reference"],
        "icon": "icon_link.png",
    },
    {
        "id": "about",
        "path": "/about",
        "name": "About",
        "description": "Read about the site and its challenges.",
        "aliases": ["about cryptobrella"],
        "tags": ["about", "help"],
        "icon": "icon_about.png",
    },
]


def get_home_catalog():
    sections = []
    section_index = {}
    tool_index = {tool["id"]: tool for tool in TOOL_CATALOG}

    for category in deepcopy(CATEGORY_DEFINITIONS):
        section = {
            "id": category["id"],
            "title": category["title"],
            "categories": [
                {
                    "id": category["id"],
                    "title": category["title"],
                    "tools": [],
                }
            ],
        }
        sections.append(section)
        section_index[category["id"]] = section["categories"][0]

    for section in sections:
        category = section["categories"][0]
        ordered_ids = CATEGORY_TOOL_ORDER[category["id"]]
        category["tools"] = [tool_index[tool_id] for tool_id in ordered_ids]

    return sections
